<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>404 Not found</title>
        <link rel="stylesheet" href="http://info26.myjino.ru/main.css">
    </head>
    <style>
        .status_code {
            font-family: sans-serif;
        }
    </style>
    <body>
        <div class="main-desc">
            <span class="inner">
                <h1 class='status_code'>404</h1>
                <h2>Здесь ничего нет</h2>
                <a href="http://info26.myjino.ru">на главную</a>
            </span>
        </div>
        
        <div class="copy">Created by Smirnov Arseniy</div>
    </body>
</html>