<footer class="footer">
    <div class="root footer__item">
        <nav class="footer__left">
            <img class="footer__logo" src="/projects/shirt/img/generic/logo.png">
            <a class="link nav-link" href="catalogue">Каталог</a>
            <a class="link nav-link" href="catalogue">Конструктор</a>
            <a class="link nav-link" href="catalogue">Доставка</a>
            <a class="link nav-link" href="catalogue">Оплата</a>
            <a class="link nav-link" href="catalogue">Котакты</a>
            <a class="link nav-link" href="catalogue">FAQ</a>
        </nav>
        <div class="footer__right"><?=date('Y')?></div>
    </div>
</footer>