<header class="header">
    <div class="root header__item">
        <nav class="header__left">
            <a class="link nav-link" href="/projects/shirt/">Главная</a>
            <a class="link nav-link" href="/projects/shirt/catalogue/">Каталог</a>
            <a class="link nav-link" href="/projects/shirt/constructor/">Конструктор</a>
            <a class="link nav-link" href="/projects/shirt/shipment/">Доставка</a>
            <a class="link nav-link" href="/projects/shirt/payment/">Оплата</a>
            <a class="link nav-link" href="/projects/shirt/contacts/">Контакты</a>
            <a class="link nav-link" href="/projects/shirt/FAQ/">FAQ</a>
        </nav>
        <div class="header__right">
            <span class="header__phone">+7 (495) 646-05-75</span>
            <a class="link cart-link" href="/projects/shirt/cart"><? include __DIR__."/../img/generic/conts-basket.svg"; ?><span class="cart-link__text">Корзина</span></a>
        </div>
    </div>
</header>