<div class="saved-screening"></div>
<div class="saved-plate">✓ Сохранено</div>
<header class="header">
    <div class="root header__item">
        <nav class="header__nav">
            <a class="link header__link" href="/projects/shirt/manage/">Главная</a>
            <a class="link header__link" href="/projects/shirt/manage/catalogue/">Каталог</a>
            <a class="link header__link" href="/projects/shirt/manage/categories/">Категории</a>
            <a class="link header__link" href="/projects/shirt/manage/types/">Типы</a>
            <a class="link header__link" href="/projects/shirt/manage/stock/">Склад</a>
            <a class="link header__link" href="/projects/shirt/manage/orders/">Заказы</a>
        </nav>
        <input type="button" class="button reset-button" value="Отменить">
        <input type="button" class="button save-button" value="Сохранить">
    </div>
</header>