<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="css/generic.css">
        <link rel="stylesheet" href="css/main.css">
        <title>Главное в Жизни</title>
        <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700|PT+Serif:700|Roboto+Condensed:700&display=swap" rel="stylesheet">
    </head>
        <? include 'templates/header.phtml'; ?>
        <main class="root main">
            <h1 class="main__header">Управление</h1>
            <div class="feature-list">
                <div class="feature-list__item"><a class="link feature-list__link" href="/projects/shirt/manage/catalogue/">Каталог</a></div>
                <div class="feature-list__item"><a class="link feature-list__link" href="/projects/shirt/manage/types/">Управление типами</a></div>
                <div class="feature-list__item"><a class="link feature-list__link" href="/projects/shirt/manage/categories/">Управление категориями</a></div>
                <div class="feature-list__item"><a class="link feature-list__link" href="/projects/shirt/manage/stock/">Посмотреть склад</a></div>
            </div>
        </main>
    </body>
</html>