<?
    rkAssert(["is_preview", "name", "tid"], $_param_);
?>

<div class="foto-cont <?=$_param_["is_preview"] ? "preview-pic" : ""?>">
    <input class="name-input" value="<?=$_param_["name"]?>" hidden>
    <img class="shirt__foto" src="/projects/shirt/img/product/<?=$_param_["tid"]?>/<?=$_param_["name"]?>">
    <div class="foto-buttons-list">
        <svg class="foto-cont__button image-mark-button" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M17 3H7C5.9 3 5.01 3.9 5.01 5L5 21L12 18L19 21V5C19 3.9 18.1 3 17 3Z"/>
        </svg>
        <svg class="foto-cont__button image-del-button" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 0C5.4 0 0 5.4 0 12C0 18.6 5.4 24 12 24C18.6 24 24 18.6 24 12C24 5.4 18.6 0 12 0ZM18 16.32L16.32 18L12 13.68L7.68 18L6 16.32L10.32 12L6 7.68L7.68 6L12 10.32L16.32 6L18 7.68L13.68 12L18 16.32Z" fill="#7D7B7B"/>
        </svg>
    </div>
</div>