<div class="row sub-row">
    <div class="cell name-cell">
        <a class="link ref-link" href="/projects/shirt/product/{tid}/">{name}</a>
    </div>
    <div class="cell quantity-cell">
        {quantity}шт
    </div>
    <div class="cell size-cell">
        {size}
    </div>
    <div class="cell checkbox-cell">
        <label class="tmpl$check-box">
            <input type="checkbox" class="tmpl$check-box__true-box sub-row__checkbox" hidden>
            <div class="tmpl$check-box__imprint"></div>
        </label>
    </div>
</div>