<?
    rkAssert(["id", "type_icon", "type_name", "type_nf_a", "type_nf_b", "type_nf_c", "active"], $_param_);
?>

<div class="row type-row type-row_sendable">
    <input class="type-id-input" value="<?= $_param_["id"] ?>" type="hidden">
    <label class="type-icon">
        <input type="file" accept=".png, .svg" class="type-icon-input" hidden>
        <div class="type-icon__hover-overlay">
            <svg class="type-icon__hover-icon" width="38" height="38" viewBox="0 0 38 38" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M19 24C21.7614 24 24 21.7614 24 19C24 16.2386 21.7614 14 19 14C16.2386 14 14 16.2386 14 19C14 21.7614 16.2386 24 19 24Z" fill="#FFFCFC" fill-opacity="0.8"/>
                <path d="M14.3125 3.375L11.4531 6.5H6.5C4.78125 6.5 3.375 7.90625 3.375 9.625V28.375C3.375 30.0938 4.78125 31.5 6.5 31.5H31.5C33.2188 31.5 34.625 30.0938 34.625 28.375V9.625C34.625
                        7.90625 33.2188 6.5 31.5 6.5H26.5469L23.6875 3.375H14.3125ZM19 26.8125C14.6875 26.8125 11.1875 23.3125 11.1875 19C11.1875 14.6875 14.6875 11.1875 19 11.1875C23.3125 11.1875
                        26.8125 14.6875 26.8125 19C26.8125 23.3125 23.3125 26.8125 19 26.8125Z" fill="#FFFCFC" fill-opacity="0.8"/>
            </svg>
        </div>
        <? require $_param_["type_icon"]; ?>
    </label>
    <div class="type-row__content">
        <div class="type-name-block">
            <input class="input type-name-input sendable" value="<?=$_param_["type_name"]?>">
            <div class="type-controls-block">
                <? requireTemplate("types/checkbox", ["active" => $_param_["active"]], "manage/templates/"); ?>
                <? requireTemplate("types/del-button", [], "manage/templates/"); ?>
            </div>
        </div>
        <div class="type-nameforms-list">
            <input class="input type-nf-input type-nf-a-input sendable" value="<?=$_param_["type_nf_a"]?>"
            ><input class="input type-nf-input type-nf-b-input sendable" value="<?=$_param_["type_nf_b"]?>"
            ><input class="input type-nf-input type-nf-c-input sendable" value="<?=$_param_["type_nf_c"]?>">
        </div>
    </div>
</div>